version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx-docker.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - ecommerce-network
    depends_on:
      - api-gateway
      - auth-service
      - user-ui

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    expose:
      - "8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - HOST=0.0.0.0
    networks:
      - ecommerce-network
    depends_on:
      - auth-service

  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    expose:
      - "6001"
    environment:
      - NODE_ENV=development
      - PORT=6001
      - HOST=0.0.0.0
      - JWT_SECRET=your-jwt-secret-key
      - JWT_EXPIRES_IN=24h
    networks:
      - ecommerce-network

  user-ui:
    build:
      context: .
      dockerfile: ./apps/user-ui/Dockerfile
    expose:
      - "3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - NEXT_PUBLIC_API_URL=http://api-gateway:8080
      - NEXT_PUBLIC_AUTH_URL=http://auth-service:6001
    networks:
      - ecommerce-network
    depends_on:
      - api-gateway
      - auth-service

networks:
  ecommerce-network:
    driver: bridge