apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: ecommerce
  labels:
    app: auth-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        version: v1
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/devicaro16/ecommerce-auth-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: AUTH_SERVICE_PORT
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: AUTH_SERVICE_HOST
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: JWT_EXPIRES_IN
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /auth/health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /auth/health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ecommerce
  labels:
    app: auth-service
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: auth-service
