apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  # API Gateway Config
  API_GATEWAY_PORT: "8080"
  API_GATEWAY_HOST: "0.0.0.0"

  # Auth Service Config
  AUTH_SERVICE_PORT: "6001"
  AUTH_SERVICE_HOST: "0.0.0.0"
  AUTH_SERVICE_NODEPORT: "30061"

  # User UI Config
  USER_UI_PORT: "3001"

  # Configurações sensíveis (JWT, Redis, URLs) estão no Secret ecommerce-secrets
