apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ui
  namespace: ecommerce
  labels:
    app: user-ui
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-ui
  template:
    metadata:
      labels:
        app: user-ui
        version: v1
    spec:
      containers:
        - name: user-ui
          image: devicaro18/ominx-user-ui:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: USER_UI_PORT
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: NEXT_PUBLIC_API_URL
            - name: NEXT_PUBLIC_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: NEXT_PUBLIC_AUTH_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-ui-service
  namespace: ecommerce
  labels:
    app: user-ui
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30301
      protocol: TCP
      name: http
  selector:
    app: user-ui
