apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ui
  namespace: ecommerce
  labels:
    app: user-ui
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-ui
  template:
    metadata:
      labels:
        app: user-ui
        version: v1
    spec:
      containers:
        - name: user-ui
          image: docker.io/devicaro16/user-ui:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: USER_UI_PORT
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: NEXT_PUBLIC_API_URL
            - name: NEXT_PUBLIC_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: NEXT_PUBLIC_AUTH_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-ui-service
  namespace: ecommerce
  labels:
    app: user-ui
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: user-ui
